jobs:

#RELEASE

  - name: manifest1
    type: manifest
    steps:
      - IN: image1
        #versionNumber: 1000
      - IN: tg1
      
  - name: tpdeploy1
    type: deploy
    steps:
      - IN: manifest1
      - IN: tripubcluster
      
  - name: release1
    type: release
    steps:      
      - IN: version
      - IN: tpdeploy1
      - TASK: managed
        bump: beta
         
      
  - name: runsh
    type: runSh
    steps:
      - IN: sample-script
      - IN: tg2
      - TASK:
        - script: ls
        - script: sleep 3m
